[package]
name = "surveycli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
comfy-table = "7.1.1"
crossterm = "0.27.0"
csv = "1.3.0"
serde = { version = "1.0.200", features = ["derive"] }
